export const ENVIRONMENT = process.env.NEXT_PUBLIC_ENVIRONMENT || "PROD";

// SUPABASE
export const SUPABASE_URL = process.env.NEXT_PUBLIC_SUPABASE_URL;
export const SUPABASE_ANON_KEY = process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY;
